#!/bin/bash

. resolve

docker build -t aerospike/aerospike-server-federal:${VERSION:-latest} .

# Push image
#if [ $PUSH ] && [ $PUSH -eq 1 ]; then
#  docker push aerospike/aerospike-server-federal:${VERSION:-latest}
#fi
